=== luctran23/xml-practice-2/tobao.xsd
<?xml version="1.0"?>


<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="tobao">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="baibao" minOccurs="2" maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tieude">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9\s]{10,}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="noidung">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9\s]{20,}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tacgia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="hoten">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[a-zA-Z\s]+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="tuoi">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:pattern value="\d+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="email">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[a-z0-9]+@[a-z]+\.[a-z]+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element> 
                            <xs:element name="ngaydang" type="xs:date"/> 
                            <xs:element name="loaibaibao">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="van hoa"/> 
                                        <xs:enumeration value="xa hoi"/> 
                                        <xs:enumeration value="giai tri"/> 
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="mabaibao">
                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:pattern value="\d+"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
           
</xs:schema>

=== luctran23/xml-practice-2/tobao.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="tobao.xsl"?>


<tobao
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='tobao.xsd'>
    <baibao mabaibao="1">
        <tieude>mi dang khong che dich covid rat chi la ok</tieude>
        <noidung>mi dang khong che dich covid rat chi la ok</noidung>
        <tacgia>
            <hoten>donaldtrump</hoten>
            <tuoi>79</tuoi>
            <email>donaldtrump@gmail.com</email>
        </tacgia>
        <ngaydang>2020-01-01</ngaydang>
        <loaibaibao>van hoa</loaibaibao>
    </baibao>
    <baibao mabaibao="2">
        <tieude>dich covid 19 dang duoc kiem soat tot o tren the gioi</tieude>
        <noidung>dich covid 19 dang duoc kiem soat tot o tren the gioi</noidung>
        <tacgia>
            <hoten>tran van tom</hoten>
            <tuoi>20</tuoi>
            <email>tom@gmail.com</email>
        </tacgia>
        <ngaydang>2021-01-01</ngaydang>
        <loaibaibao>van hoa</loaibaibao>
    </baibao>
    <baibao mabaibao="3">
        <tieude>dich covid 19 dang duoc kiem soat tot o tren the gioi</tieude>
        <noidung>dich covid 19 dang duoc kiem soat tot o tren the gioi</noidung>
        <tacgia>
            <hoten>cua</hoten>
            <tuoi>21</tuoi>
            <email>tomcuja@gmail.com</email>
        </tacgia>
        <ngaydang>2023-02-02</ngaydang>
        <loaibaibao>xa hoi</loaibaibao>
    </baibao>

</tobao>
